<a href="https://colab.research.google.com/github/JeffTiong1031/data_science_w1/blob/main/Tuto_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. Create a numpy array of size 2 x 2
arr_2x2 = np.array([[1, 2],
                    [3, 4]])
print("2 x 2 array:\n", arr_2x2)

2 x 2 array:
 [[1 2]
 [3 4]]


In [2]:
# 2. Create a random numpy array of size 3 x 4
rand_3x4 = np.random.rand(3, 4)
print("\nRandom 3 x 4 array:\n", rand_3x4)


Random 3 x 4 array:
 [[0.38486007 0.03105355 0.08255487 0.41359741]
 [0.77369025 0.70328155 0.31960287 0.89161768]
 [0.64004297 0.59943542 0.68279774 0.47977824]]


In [3]:
# 3. Create a numpy array of ones and a numpy array of zeros
ones_arr = np.ones((3, 3))
zeros_arr = np.zeros((3, 3))
print("\nArray of ones:\n", ones_arr)
print("\nArray of zeros:\n", zeros_arr)


Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# 4. Create a random numpy array of size 6 x 3 and transpose it
rand_6x3 = np.random.rand(6, 3)
transpose_6x3 = rand_6x3.T
print("\nRandom 6 x 3 array:\n", rand_6x3)
print("\nTransposed array (3 x 6):\n", transpose_6x3)


Random 6 x 3 array:
 [[0.25074687 0.41083654 0.7361563 ]
 [0.06095732 0.15723262 0.84619185]
 [0.33483333 0.34024024 0.91675586]
 [0.72413885 0.05051725 0.61334333]
 [0.03455262 0.00103211 0.94970117]
 [0.36472472 0.15916023 0.68177538]]

Transposed array (3 x 6):
 [[0.25074687 0.06095732 0.33483333 0.72413885 0.03455262 0.36472472]
 [0.41083654 0.15723262 0.34024024 0.05051725 0.00103211 0.15916023]
 [0.7361563  0.84619185 0.91675586 0.61334333 0.94970117 0.68177538]]


In [5]:
# 5. Create two random numpy arrays of size n x p and p x m and then compute the dot product
n, p, m = 2, 3, 4
A = np.random.rand(n, p)
B = np.random.rand(p, m)
dot_product = np.dot(A, B)

print("\nMatrix A (",n,"x",p,"):\n", A)
print("\nMatrix B (",p,"x",m,"):\n", B)
print("\nDot Product (A x B):\n", dot_product)


Matrix A ( 2 x 3 ):
 [[0.52616037 0.85937777 0.99320159]
 [0.25143649 0.84398121 0.90460128]]

Matrix B ( 3 x 4 ):
 [[0.15204817 0.18099216 0.81643255 0.40655101]
 [0.52563712 0.67737185 0.41284861 0.36828074]
 [0.76348174 0.63483002 0.53928658 0.78468038]]

Dot Product (A x B):
 [[1.29001386 1.3078634  1.31998766 1.30974911]
 [1.17250487 1.1914652  1.04155673 1.12286666]]
